"""Import Outpost art/audio and build the small material set in Unreal.

Run from Unreal Editor 5.8 with::

    UnrealEditor-Cmd.exe Outpost2D.uproject -run=pythonscript -script=Tools/import_assets.py

The script only replaces assets at the exact paths listed below.  It expects
``SourceArt/arena.png`` and ``SourceArt/sprites.png`` to be supplied by the
art pipeline and the WAVs to have been generated by ``generate_audio.py``.
"""

from __future__ import annotations

import os
import sys
import traceback
from pathlib import Path

import unreal


ART_DIR = "/Game/Outpost/Art"
AUDIO_DIR = "/Game/Outpost/Audio"
MAP_PATH = "/Game/Outpost/Maps/OutpostArena"
PROJECT_DIR = Path(unreal.Paths.project_dir()).resolve()
SOURCE_ART_DIR = PROJECT_DIR / "SourceArt"
SOURCE_AUDIO_DIR = SOURCE_ART_DIR / "sounds"


def _log(message: str) -> None:
    print(f"[OutpostAssetImport] {message}")


def _fail(message: str) -> None:
    raise RuntimeError(message)


def _asset_exists(path: str) -> bool:
    return bool(unreal.EditorAssetLibrary.does_asset_exist(path))


def _delete_exact_asset(path: str) -> None:
    if not _asset_exists(path):
        return
    _log(f"Replacing existing project asset: {path}")
    if not unreal.EditorAssetLibrary.delete_asset(path):
        _fail(f"Could not replace existing asset at exact path {path}")


def _import_file(source: Path, destination_path: str, asset_name: str):
    if not source.is_file():
        _fail(f"Required source file is missing: {source}")
    task = unreal.AssetImportTask()
    task.set_editor_property("filename", str(source))
    task.set_editor_property("destination_path", destination_path)
    task.set_editor_property("destination_name", asset_name)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("automated", True)
    task.set_editor_property("save", False)
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
    imported_paths = list(task.get_editor_property("imported_object_paths"))
    expected = f"{destination_path}/{asset_name}"
    if not imported_paths:
        _fail(f"Unreal did not report an imported asset for {source}")
    loaded = unreal.load_asset(expected)
    if loaded is None:
        loaded = unreal.load_asset(imported_paths[0])
    if loaded is None:
        _fail(f"Imported asset could not be loaded at {expected}; reported {imported_paths}")
    if not unreal.EditorAssetLibrary.save_loaded_asset(loaded):
        _fail(f"Could not save imported asset {expected}")
    return loaded


def _configure_texture(texture) -> None:
    # These are UTexture2D editor properties exposed by the UE 5.8 Python API.
    texture.set_editor_property("srgb", True)
    texture.set_editor_property("compression_settings", unreal.TextureCompressionSettings.TC_DEFAULT)
    texture.set_editor_property("mip_gen_settings", unreal.TextureMipGenSettings.TMGS_NO_MIPMAPS)
    texture.set_editor_property("never_stream", False)
    # Keep imported alpha available for M_Sprite's opacity input.
    texture.set_editor_property("compression_no_alpha", False)
    if not unreal.EditorAssetLibrary.save_loaded_asset(texture):
        _fail(f"Could not save texture settings for {texture.get_path_name()}")


def _new_material(name: str):
    path = f"{ART_DIR}/{name}"
    _delete_exact_asset(path)
    factory = unreal.MaterialFactoryNew()
    material = unreal.AssetToolsHelpers.get_asset_tools().create_asset(name, ART_DIR, unreal.Material, factory)
    if material is None:
        _fail(f"Could not create material {path}")
    material.set_editor_property("material_domain", unreal.MaterialDomain.MD_SURFACE)
    material.set_editor_property("shading_model", unreal.MaterialShadingModel.MSM_UNLIT)
    return material


def _expression(material, expression_class, x: int, y: int):
    node = unreal.MaterialEditingLibrary.create_material_expression(material, expression_class, x, y)
    if node is None:
        _fail(f"Could not create material expression {expression_class.__name__} in {material.get_path_name()}")
    return node


def _parameter(node, name: str, value=None) -> None:
    node.set_editor_property("parameter_name", name)
    if value is not None:
        node.set_editor_property("default_value", value)


def _connect(source, source_output: str, destination, destination_input: str) -> None:
    if not unreal.MaterialEditingLibrary.connect_material_expressions(source, source_output, destination, destination_input):
        _fail(f"Could not connect {source.get_name()}:{source_output} to {destination.get_name()}:{destination_input}")


def _connect_property(source, source_output: str, material_property) -> None:
    if not unreal.MaterialEditingLibrary.connect_material_property(source, source_output, material_property):
        _fail(f"Could not connect {source.get_name()}:{source_output} to {material_property}")


def _save_material(material) -> None:
    unreal.MaterialEditingLibrary.recompile_material(material)
    if not unreal.EditorAssetLibrary.save_loaded_asset(material):
        _fail(f"Could not save material {material.get_path_name()}")


def _create_floor_material(arena_texture):
    material = _new_material("M_Floor")
    sample = _expression(material, unreal.MaterialExpressionTextureSampleParameter2D, -300, 0)
    _parameter(sample, "SpriteTexture")
    sample.set_editor_property("texture", arena_texture)
    _connect_property(sample, "RGB", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    _save_material(material)


def _create_sprite_material(sprite_texture):
    material = _new_material("M_Sprite")
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_TRANSLUCENT)
    material.set_editor_property("two_sided", True)

    coordinates = _expression(material, unreal.MaterialExpressionTextureCoordinate, -900, 0)
    uv_scale = _expression(material, unreal.MaterialExpressionVectorParameter, -900, 170)
    _parameter(uv_scale, "UVScale", unreal.LinearColor(0.5, 0.5, 0.0, 0.0))
    uv_scale_rg = _expression(material, unreal.MaterialExpressionComponentMask, -700, 170)
    uv_scale_rg.set_editor_property("r", True)
    uv_scale_rg.set_editor_property("g", True)
    uv_scale_rg.set_editor_property("b", False)
    uv_scale_rg.set_editor_property("a", False)
    uv_multiply = _expression(material, unreal.MaterialExpressionMultiply, -600, 70)
    uv_offset = _expression(material, unreal.MaterialExpressionVectorParameter, -900, 340)
    _parameter(uv_offset, "UVOffset", unreal.LinearColor(0.0, 0.0, 0.0, 0.0))
    uv_offset_rg = _expression(material, unreal.MaterialExpressionComponentMask, -700, 340)
    uv_offset_rg.set_editor_property("r", True)
    uv_offset_rg.set_editor_property("g", True)
    uv_offset_rg.set_editor_property("b", False)
    uv_offset_rg.set_editor_property("a", False)
    uv_add = _expression(material, unreal.MaterialExpressionAdd, -350, 70)
    sample = _expression(material, unreal.MaterialExpressionTextureSampleParameter2D, -80, 70)
    _parameter(sample, "SpriteTexture")
    sample.set_editor_property("texture", sprite_texture)

    _connect(coordinates, "", uv_multiply, "A")
    _connect(uv_scale, "", uv_scale_rg, "")
    _connect(uv_scale_rg, "", uv_multiply, "B")
    _connect(uv_multiply, "", uv_add, "A")
    _connect(uv_offset, "", uv_offset_rg, "")
    _connect(uv_offset_rg, "", uv_add, "B")
    _connect(uv_add, "", sample, "UVs")

    tint = _expression(material, unreal.MaterialExpressionVectorParameter, -80, 310)
    _parameter(tint, "Tint", unreal.LinearColor(1.0, 1.0, 1.0, 1.0))
    color_multiply = _expression(material, unreal.MaterialExpressionMultiply, 230, 70)
    _connect(sample, "RGB", color_multiply, "A")
    _connect(tint, "", color_multiply, "B")
    _connect_property(color_multiply, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)

    alpha_multiply = _expression(material, unreal.MaterialExpressionMultiply, 470, 260)
    _connect(sample, "A", alpha_multiply, "A")
    _connect(tint, "A", alpha_multiply, "B")
    _connect_property(alpha_multiply, "", unreal.MaterialProperty.MP_OPACITY)
    _save_material(material)


def _create_flat_material():
    material = _new_material("M_Flat")
    material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_TRANSLUCENT)
    material.set_editor_property("two_sided", True)
    tint = _expression(material, unreal.MaterialExpressionVectorParameter, -200, 0)
    _parameter(tint, "Tint", unreal.LinearColor(1.0, 1.0, 1.0, 1.0))
    _connect_property(tint, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    _connect_property(tint, "A", unreal.MaterialProperty.MP_OPACITY)
    _save_material(material)


def _create_map() -> None:
    # LevelEditorSubsystem.new_level is the UE 5.8 replacement for the
    # deprecated EditorLevelLibrary.new_level API.
    _delete_exact_asset(MAP_PATH)
    subsystem = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if subsystem is None or not subsystem.new_level(MAP_PATH, False):
        _fail(f"Could not create blank level {MAP_PATH}")
    if not subsystem.save_current_level():
        _fail(f"Could not save level {MAP_PATH}")


def main() -> None:
    _log(f"Project directory: {PROJECT_DIR}")
    unreal.EditorAssetLibrary.make_directory(ART_DIR)
    unreal.EditorAssetLibrary.make_directory(AUDIO_DIR)
    unreal.EditorAssetLibrary.make_directory("/Game/Outpost/Maps")

    arena = _import_file(SOURCE_ART_DIR / "arena.png", ART_DIR, "T_Arena")
    sprites = _import_file(SOURCE_ART_DIR / "sprites.png", ART_DIR, "T_Sprites")
    _configure_texture(arena)
    _configure_texture(sprites)

    for filename in (
        "S_shot.wav", "S_mine.wav", "S_forge.wav", "S_upgrade.wav", "S_lift.wav",
        "S_place.wav", "S_hit.wav", "S_hurt.wav", "S_wave.wav", "S_win.wav", "S_lose.wav",
    ):
        audio_asset = _import_file(SOURCE_AUDIO_DIR / filename, AUDIO_DIR, Path(filename).stem)
        _log(f"Imported {audio_asset.get_path_name()}")

    _create_floor_material(arena)
    _create_sprite_material(sprites)
    _create_flat_material()
    _create_map()
    _log("Completed Outpost art, materials, audio, and blank map import.")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as error:
        _log(f"ERROR: {error}")
        traceback.print_exc()
        sys.exit(1)
